# Generated by Django 5.2.16 on 2026-10-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_add_harsh_student"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lecture",
            name="unique_lecture",
        ),
        migrations.RemoveField(
            model_name="lecture",
            name="section",
        ),
        migrations.AddField(
            model_name="lecture",
            name="sections",
            field=models.ManyToManyField(
                related_name="lectures", to="attendance.section"
            ),
        ),
        migrations.AddConstraint(
            model_name="lecture",
            constraint=models.UniqueConstraint(
                fields=("faculty", "subject", "lecture_date", "start_time", "end_time"),
                name="unique_lecture",
            ),
        ),
    ]
